#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_debug_printf : enable

#include "commons.h"

layout(set = 0, binding = 2, scalar) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer SpherePrims { SpherePrimitive spheres[]; };

hitAttributeEXT SphereHitAttribs sphere_attribs;

void main() {
	if (gl_PrimitiveID < 5) {
		debugPrintfEXT("sphere.rint: prim=%u\n", gl_PrimitiveID);
	}
	SpherePrims sphere_buf = SpherePrims(scene_desc.sphere_prims_addr);
	SpherePrimitive s = sphere_buf.spheres[gl_PrimitiveID];

	vec3 O = gl_WorldRayOriginEXT - s.center;
	float l = 1.0 / length(gl_WorldRayDirectionEXT);
	vec3 D = gl_WorldRayDirectionEXT * l;

	float b = dot(O, D);
	float c = dot(O, O) - s.radius * s.radius;
	float disc = b * b - c;

	if (disc <= 0.0) return;

	float sdisc = sqrt(disc);
	float root1 = -b - sdisc;
	float root11 = 0.0;
	bool check_second = true;

	bool do_refine = abs(root1) > 10.0 * s.radius;
	if (do_refine) {
		vec3 O1 = O + root1 * D;
		b = dot(O1, D);
		c = dot(O1, O1) - s.radius * s.radius;
		disc = b * b - c;
		if (disc > 0.0) {
			sdisc = sqrt(disc);
			root11 = -b - sdisc;
		}
	}

	float t = (root1 + root11) * l;
	if (t > gl_RayTminEXT && t < gl_RayTmaxEXT) {
		sphere_attribs.normal = normalize(O + (root1 + root11) * D);
		sphere_attribs.materialIndex = uint(gl_PrimitiveID);
		if (reportIntersectionEXT(t, 0)) {
			check_second = false;
		}
	}

	if (check_second) {
		float root2 = (-b + sdisc) + (do_refine ? root1 : 0.0);
		t = root2 * l;
		if (t > gl_RayTminEXT && t < gl_RayTmaxEXT) {
			sphere_attribs.normal = normalize(O + root2 * D);
			sphere_attribs.materialIndex = uint(gl_PrimitiveID);
			reportIntersectionEXT(t, 0);
		}
	}
}
