#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#include "restirdi_commons.h"
#include "restirdi_commons.glsl"

void main() {
    const float max_r = 30;                    // paper biased variant: 30px radius
    const float depth_threshold = 0.1;         // paper: normalized depth within 10%
    const float angle_threshold = 25 * PI / 180;
    const float num_neighbor_samples = 5;
    load_g_buffer();
    const float depth_q = length(pos - origin);  // current pixel depth from camera
    const RestirReservoir curr_reservoir = passthrough_reservoirs.d[pixel_idx];
    RestirReservoir r;
    init_reservoir(r);
    if (curr_reservoir.W != 0) {
        combine_reservoir(r, curr_reservoir);
        uint num_samples = curr_reservoir.m;
        for (int i = 0; i < num_neighbor_samples; i++) {
            // Choose a neighbor pixel
            const float randa = rand(seed) * 2 * PI;
            const float randr = sqrt(rand(seed)) * max_r;
            ivec2 rand_offset =
                ivec2(floor(cos(randa) * randr), floor(sin(randa) * randr));
            const ivec2 coords =
                clamp(ivec2(gl_LaunchIDEXT.xy) + rand_offset, ivec2(0),
                      ivec2(gl_LaunchSizeEXT.xy) - 1);
            const uint neighbor_idx = coords.x * pc.size_y + coords.y;

            // Geometric similarity check (paper biased Alg. 5)
            const RestirGBufferData neighbor_gb = gbuffer.d[neighbor_idx];
            const float depth_n = length(neighbor_gb.pos - origin);
            if (depth_n == 0.0 || abs(depth_q / depth_n - 1.0) > depth_threshold ||
                dot(neighbor_gb.normal, normal) < cos(angle_threshold)) {
                continue;
            }

            const RestirReservoir r_n = passthrough_reservoirs.d[neighbor_idx];
            combine_reservoir(r, r_n);
            num_samples += r_n.m;
        }
        r.m = num_samples;
        const float phat = calc_p_hat(r) * r.m;
        r.W = phat == 0 ? 0 : r.w_sum / phat;
    }
    spatial_reservoirs.d[pixel_idx].w_sum = r.w_sum;
    spatial_reservoirs.d[pixel_idx].W = r.W;
    spatial_reservoirs.d[pixel_idx].m = r.m;
    spatial_reservoirs.d[pixel_idx].s = r.s;
}